### ISSUE TITLE
Error en el comando s!cqueue

### ISSUE THREAD

**Issue by MrDevsaider** [scripthubteam/Script-Hub-Free#18]
- Pendiente por corregir

**Comment by tati1206** [comment]
Devsaider, se agradecería que agregues mas detalles sobre el issue. De esta forma conseguimos que otras personas entiendan el problema y puedan contribuir.

**Comment by MrDevsaider** [comment]
> Devsaider, se agradecería que agregues mas detalles sobre el issue. De esta forma conseguimos que otras personas entiendan el problema y puedan contribuir.

El issue está aquí solo para automatizar las tareas pendientes pero igualmente lo explicaré:

El error origina `undefined` al leer el get de la ID del bot.
```js
 let queue = await client.db.bots.find({ approvedDate: 0 }).exec();
 queue
    .sort((a, b) => a.nQueue - b.nQueue)
    .forEach((bot) => {
      out += `> **${bot.nQueue}**. ${msg.guild.members.get(bot.botId).user.tag} - ${msg.guild.members.get(bot.ownerId).user.tag} - \`${bot.prefix}\`\n`;
    });
```
Las tatipruebas:
![image](https://user-images.githubusercontent.com/14142484/69397086-5ba90a80-0caa-11ea-97d4-2e0ec6408bc0.png)
