### ISSUE TITLE
Error en cqueue

### ISSUE THREAD

**Issue by Laauuu** [scripthubteam/Script-Hub-Free#20]
Al utilizar el comando en número de veces impar. (La primera vez, la tercera, la quinta...) solo despliega el primer bot en la queue.

Se espera obtener cada bot en la lista al utilizar el comando.

**Comment by tati1206** [comment]
Cuando trato de reproducir el bug no ocurre este problema, hay algun otro detalle que te estés olvidando?

**Comment by Laauuu** [comment]
No. Podes verlo en el canal de test-bot en la sección de Staff.
