### ISSUE TITLE
Error en Actualizar la info del Bot

### ISSUE THREAD

**Issue by SoyMario97** [scripthubteam/Script-Hub-Free#35]
Problema: No me detecta como Owner ni al Staff de Script Hub los detecta
Que espero: Espero que solucionen el Problema

Atte: Mario

**Comment by Laauuu** [comment]
¿Comando?

**Comment by SoyMario97** [comment]
s!infobot <MencionAlBot> desc:<Descripción>

**Comment by wwmon** [comment]
Debes proporcionar más información sobre el problema o cerraremos el issue, asegúrate de seguir bien el formato de issues. https://github.com/scripthubteam/Script-Hub-Free#como-reportar-issues

**Comment by SoyMario97** [comment]
Resultado obtenido: No me detecta como Owner ni al Staff de Script Hub los detecta
Resultado esperado: Espero que solucionen el Problema
Información extra: Saludos a Script Hub
Atte: Mario

**Comment by wwmon** [comment]
Cómo "Resultado Esperado" nos referimos a lo que esperas que haga el comando, no lo que esperas que hagamos nosotros. También necesitamos información sobre, si tú eres el dueño del bot (Si adjuntas una imagen mejor) y cómo reproducir el error. (Lo que hiciste para que resultara)

**Comment by SoyMario97** [comment]
https://imgur.com/3spTIpN
https://imgur.com/bzKinpy
https://imgur.com/vgr3soB

**Comment by wwmon** [comment]
Vale, gracias por reportar el fallo, estaremos trabajando en ello.

**Comment by wwmon** [comment]
El problema ha sido resuelto, muchas gracias por su paciencia.

**Comment by MrDevsaider** [comment]
Referencias:
#37
