### ISSUE TITLE
Problemas con las sugerencias

### ISSUE THREAD

**Issue by Sebasorqui03** [scripthubteam/Script-Hub-Free#40]
**Problemas con las sugerencias**
Al parecer el comando ``sugerir`` no envia la sugerencia al canal de sugerencias.
No he reisaso el code pero creo que tiene algun error

**Comment by Laauuu** [comment]
Mal formato de issue. Vuelve a formularlo tomando en cuenta lo siguiente:
https://github.com/scripthubteam/Script-Hub-Free#como-reportar-issues
